// "use client";



import { Providers } from "@/components/Proveders";
// import { notFound } from 'next/navigation';
import Header from "@/components/Header";
import type { Metadata } from "next";
import {NextIntlClientProvider} from 'next-intl';
import {getMessages} from 'next-intl/server';

import i18nConfig from "@/i18n/i18n.config";
// import { useCurrentLocale } from 'next-i18n-router/client';



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { notFound } from 'next/navigation';

// const locale = useCurrentLocale(i18nConfig);
export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: {locale: string};
}>) {
  const locale = params?.locale; 

  if (!i18nConfig.locales.includes(locale)) {
    notFound();
  }

  const messages = await getMessages();

  return (
    <div className="h-screen flex flex-col">
      <Providers>
        <NextIntlClientProvider messages={messages}>
          <Header />
          {children}
        </NextIntlClientProvider>
      </Providers>    
    </div>    
  );
}

